{
 "title": "Sepehr_Micro_Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "MicroService",
    "query": {}
   },
   { "name": "Filter" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{Micro=~\"$MicroService\"} |= `$Filter` | json | line_format \"🕒 Time: {{.timestamp}}\\n🔹 Level: {{.level}}\\n📍 Trace ID: {{.CorrelationId}}\\n👤 User: {{.UserName}} | 🛡 Role: {{.Role}} | 🆔 ID: {{.UserID}}\\n🌍 IP: {{.UserIP}}\\n🔄 Method: {{.Method}}\\n📌 Endpoint: {{.Endpoint}}\\n🔎 Query: {{.Query}}\\n💬 Message: {{.Message}}\\n💡 Source: {{.SourceContext}}\\n🔥 Exception: {{.Exception}}\"\r\n\r\n"
    }
   ]
  },
  { "title": "LogDetails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (Method) (\r\n  count_over_time(\r\n    {Micro=~\"$MicroService\"} \r\n    | json Method \r\n    | drop __error__ \r\n    [$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "LogLevel Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (\r\n  count_over_time(\r\n    {Micro=~\"$MicroService\"} \r\n    | json \r\n    | drop __error__ \r\n    | level != \"\" \r\n  [${__range}]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Service Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Micro) (count_over_time({Micro=~\"$MicroService\"} |logfmt |drop __error__  | Micro =~ `.+` [$__range]))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 11 },
   "targets": [
    {
     "expr": "sum by(Method) (\r\n  count_over_time({Micro=~\"$MicroService\"} | json | drop __error__ [$__range])\r\n)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(Micro, Method, level) (count_over_time({Micro=~\"$MicroService\"}  | json |drop __error__  [$__range]))"
    }
   ]
  }
 ]
}