ARG VERSION=1.5.8
FROM 185.89.22.58:8082/repository/parseh-docker-private/minimal_ui_pcmms:${VERSION} as builder
# WORKDIR /app
# # Set environment variables
# # Set build arguments

# ENV REACT_APP_PublishVersion=1.5.3

# RUN npm run build