From 185.89.22.58:8082/repository/parseh-docker-private/iconify/api:latest

# RUN npm config delete proxy 2>/dev/null || true
# RUN npm config delete https-proxy 2>/dev/null || true

# ENV HTTP_PROXY=
# ENV HTTPS_PROXY=
# ENV http_proxy=
# ENV https_proxy=


# RUN npm config set registry https://registry.npmjs.org/



# WORKDIR /data


# CMD ["node", "--expose-gc", "lib/index.js"]